import styles from './Contact.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'

const Contact = () => {
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Emre Bican | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.content}>
        <h3>Contact</h3>
        <h1>Get in touch</h1>
        <div className={styles.wrapper}>
          <div className={styles.leftWrapper}>
            <Image
              src="/assets/contact2.jpg"
              alt="image"
              layout="fill"
              className={
                loading
                  ? 'duration-700 ease-in-out grayscale blur-xl'
                  : 'duration-700 ease-in-out grayscale-0 blur-0'
              }
              onLoadingComplete={() => setLoading(false)}
            />
          </div>
          <div className={styles.rightWrapper}>
            <h2 className={styles.title}>Let&apos;s Talk</h2>
            <form>
              <main>
                <div className="flex flex-col">
                  <label>Name</label>
                  <input type="text" />
                </div>
                <div className="flex flex-col">
                  <label>Phone Number</label>
                  <input type="text" />
                </div>
              </main>
              <div className="flex flex-col py-2">
                <label>Email</label>
                <input type="text" />
              </div>
              <div className="flex flex-col py-2">
                <label>Comments</label>
                <textarea rows={10}></textarea>
              </div>
              <button>Send</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Contact
