import styles from './Contact.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import { TForm } from '../../constants/types-interfaces'

const Contact = () => {
  const [loading, setLoading] = useState<boolean>(true)
  const [formValue, setFormValue] = useState<TForm>({
    name: '',
    phone: '',
    email: '',
    comments: ''
  })
  const router = useRouter()

  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })
  }, [])

  useEffect(() => {}, [])

  const handleForm = () => {
    setFormValue({ name: '', phone: '', email: '', comments: '' })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Emre Bican | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.content}>
        <h3>Contact</h3>
        <h1>Get in touch</h1>
        <div className={styles.wrapper}>
          <div className={styles.leftWrapper}>
            <Image
              src="/assets/contact2.jpg"
              alt="image"
              layout="fill"
              className={
                loading
                  ? 'duration-700 ease-in-out grayscale blur-xl'
                  : 'duration-700 ease-in-out grayscale-0 blur-0'
              }
              onLoadingComplete={() => setLoading(false)}
            />
          </div>
          <div className={styles.rightWrapper}>
            <h2 className={styles.title}>Let&apos;s Talk</h2>
            <form
              lang="en"
              action="https://getform.io/f/57933c42-58ce-46e3-906c-d1fef1047c60"
              method="POST"
              encType="multipart/form-data"
            >
              <main>
                <div className="flex flex-col">
                  <label>Name</label>
                  <input type="text" name="name" required />
                </div>
                <div className="flex flex-col">
                  <label>Phone Number</label>
                  <input type="text" name="phone" required />
                </div>
              </main>
              <div className="flex flex-col py-2">
                <label>Email</label>
                <input type="email" name="email" required />
              </div>
              <div className="flex flex-col py-2">
                <label>Comments</label>
                <textarea rows={10} name="comments" required></textarea>
              </div>
              <button type="submit" onClick={handleForm}>
                Send
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Contact
