import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione officia
      culpa voluptate, porro tempore excepturi animi cumque sapiente doloremque
      voluptatum qui sequi at rem enim? Velit pariatur iste quasi voluptatum
      numquam! Obcaecati tempore explicabo vitae, in totam quia. Id numquam
      natus iure illum omnis officiis hic eius excepturi ipsum, porro tenetur
      corporis ipsam quos asperiores, beatae cupiditate ullam maxime adipisci
      quam inventore, vel eaque perspiciatis fugiat atque. Exercitationem
      reprehenderit quae deleniti saepe dolor ducimus neque! At voluptate,
      assumenda dolore sapiente similique eveniet quis, veritatis suscipit
      pariatur aspernatur consectetur repellendus voluptatem hic saepe illo modi
      facilis consequuntur, deserunt ipsam ut perspiciatis!
    </div>
  )
}
